version: "3.7"
services:

  zookeeper:
    container_name: zookeeper
    restart: always
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka-server
    restart: always
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE= true
      - KAFKA_CREATE_TOPICS= "input, output"
    depends_on:
      - zookeeper   

  nginx_proxy:
    container_name: nginx_proxy
    image: nginx:1.25-alpine
    ports:
      - 8080:80  # Expose port 8080, forward to Nginx's port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shiny_front

  shiny_front:
    build: .
    container_name: shiny_front
    volumes:
      - ./shiny_front.r:/app/app.R
    # NO PORTS EXPOSED. Nginx will talk to this container directly.
    command: R -e "shiny::runApp('/app/app.R', host='0.0.0.0', port=3838)"
    depends_on:
      - kafka

  shiny_front_two:
    build: .
    container_name: shiny_front_two
    volumes:
      - ./shiny_front.r:/app/app.R
    ports:
      - 8280:3838
    command: R -e "shiny::runApp('/app/app.R', host='0.0.0.0', port=3838)"
    depends_on:
      - kafka

  shiny_back:
    build: .
    container_name: shiny_back
    volumes:
      - ./shiny_back.r:/app/back.R
    command: Rscript /app/back.R
    depends_on:
      - kafka